### ISSUE TITLE
Specify which python: python3 needed to install

### ISSUE THREAD

**Issue by aracca994** [MagriLab/KolSol#36]
I managed to install the solver with python3, so that in Ubuntu the command needs to be 

sudo python3 setup.py install

as in Python 2.x with 'python setup.py install' the following error pops up 

Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    with open('README.md', encoding='utf8') as readme_file:
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by danielkelshaw** [comment]
If you're running this within a virtual environment or you have aliased: `export python="python3"` in your `.bashrc`/`.zshrc` file then the command will work as intended.

I'll put a small comment in the `README.md` which specifies that you must be running on some version of `python3`.
